spring:
  application:
    name: pyramid-game-service
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DB_URL}
      password: ${DB_PASSWORD}
      pool-size: 30
      username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: ${PORT:8180}

